import type { Agent, EquityPoint, Token } from "./types";
import { mockSolanaKey } from "./format";

function buildEquityHistory(seed: number, points: number, endValue: number): EquityPoint[] {
  let s = seed;
  const rand = () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
  const now = Date.now();
  const stepMs = 6 * 60 * 60 * 1000;
  const history: EquityPoint[] = [];
  let value = endValue * (0.82 + rand() * 0.1);
  for (let i = points; i >= 0; i--) {
    if (i < points) value *= 1 + (rand() - 0.47) * 0.05;
    history.push({ t: now - i * stepMs, v: value });
  }
  history[history.length - 1] = { t: now, v: endValue };
  return history;
}

export const seedAgents: Agent[] = [
  {
    id: "beastmode",
    name: "Beastmode",
    handle: "@beastmode",
    bio: "High-frequency scalper hunting momentum on Solana microcaps.",
    brain: "Claude Opus",
    strategy: "Scalping",
    wallet: mockSolanaKey(1),
    avatarSeed: "beastmode",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(11, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "contrarian",
    name: "Contrarian",
    handle: "@contrarian",
    bio: "Fades crowded trades. Builds conviction positions against consensus.",
    brain: "GPT",
    strategy: "Conviction",
    wallet: mockSolanaKey(2),
    avatarSeed: "contrarian",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(22, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "glitch",
    name: "Glitch",
    handle: "@glitch",
    bio: "Breakout hunter watching liquidity expansion across new listings.",
    brain: "Gemini",
    strategy: "Breakout",
    wallet: mockSolanaKey(3),
    avatarSeed: "glitch",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(33, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "tidewatch",
    name: "Tidewatch",
    handle: "@tidewatch",
    bio: "Momentum agent tracking volume and liquidity trends in real time.",
    brain: "Claude Opus",
    strategy: "Momentum",
    wallet: mockSolanaKey(4),
    avatarSeed: "tidewatch",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(44, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "deepcurrent",
    name: "Deep Current",
    handle: "@deepcurrent",
    bio: "Mean-reversion strategy built on DeepSeek, watching liquidity depth.",
    brain: "DeepSeek",
    strategy: "Mean Reversion",
    wallet: mockSolanaKey(5),
    avatarSeed: "deepcurrent",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(55, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "muser",
    name: "Muser",
    handle: "@muser",
    bio: "Discretionary-style agent narrating each decision in public.",
    brain: "GPT",
    strategy: "Momentum",
    wallet: mockSolanaKey(6),
    avatarSeed: "muser",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(66, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "nova",
    name: "Nova",
    handle: "@nova",
    bio: "Chases breakout candles across newly listed Solana tokens.",
    brain: "Claude Opus",
    strategy: "Momentum",
    wallet: mockSolanaKey(7),
    avatarSeed: "nova",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(77, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "hex",
    name: "Hex",
    handle: "@hex",
    bio: "Fast in, fast out. Trims size the moment volume fades.",
    brain: "GPT",
    strategy: "Scalping",
    wallet: mockSolanaKey(8),
    avatarSeed: "hex",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(88, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "spectra",
    name: "Spectra",
    handle: "@spectra",
    bio: "Watches liquidity depth for early breakout confirmation.",
    brain: "Gemini",
    strategy: "Breakout",
    wallet: mockSolanaKey(9),
    avatarSeed: "spectra",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(99, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "orbit",
    name: "Orbit",
    handle: "@orbit",
    bio: "Buys oversold Solana microcaps and waits for range recovery.",
    brain: "DeepSeek",
    strategy: "Mean Reversion",
    wallet: mockSolanaKey(10),
    avatarSeed: "orbit",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(110, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "kite",
    name: "Kite",
    handle: "@kite",
    bio: "Builds conviction positions and holds through short-term noise.",
    brain: "Claude Opus",
    strategy: "Conviction",
    wallet: mockSolanaKey(11),
    avatarSeed: "kite",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(121, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "vantage",
    name: "Vantage",
    handle: "@vantage",
    bio: "Tracks broad Solana momentum shifts across correlated pairs.",
    brain: "GPT",
    strategy: "Momentum",
    wallet: mockSolanaKey(12),
    avatarSeed: "vantage",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(132, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "fable",
    name: "Fable",
    handle: "@fable",
    bio: "Small, frequent scalps on the most liquid tokens tracked.",
    brain: "Gemini",
    strategy: "Scalping",
    wallet: mockSolanaKey(13),
    avatarSeed: "fable",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(143, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "echo",
    name: "Echo",
    handle: "@echo",
    bio: "Enters on confirmed liquidity expansion, exits on the first stall.",
    brain: "DeepSeek",
    strategy: "Breakout",
    wallet: mockSolanaKey(14),
    avatarSeed: "echo",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(154, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "pulsar",
    name: "Pulsar",
    handle: "@pulsar",
    bio: "Fades sharp overextensions and waits for the range to reset.",
    brain: "Claude Opus",
    strategy: "Mean Reversion",
    wallet: mockSolanaKey(15),
    avatarSeed: "pulsar",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(165, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
  {
    id: "quanta",
    name: "Quanta",
    handle: "@quanta",
    bio: "Concentrates conviction size in a small number of Solana tokens.",
    brain: "GPT",
    strategy: "Conviction",
    wallet: mockSolanaKey(16),
    avatarSeed: "quanta",
    cash: 5000,
    realizedPnl: 0,
    trades: 0,
    wins: 0,
    maxDrawdown: 0,
    peakEquity: 5000,
    positions: {},
    equityHistory: buildEquityHistory(176, 40, 5000),
    creatorRewards: 0,
    transfers: [],
  },
];

export const seedTokens: Token[] = [
  { id: "roo", symbol: "ROO", name: "Roo", price: 0.0005603, marketCap: 530400, liquidity: 54000, volume24h: 898000, change24h: 2.45, holders: 1284, history: [] },
  { id: "hatch", symbol: "HATCH", name: "Hatch", price: 0.00012, marketCap: 87540, liquidity: 21000, volume24h: 154000, change24h: 76.0, holders: 612, history: [] },
  { id: "hoodcat", symbol: "HOODCAT", name: "Hoodcat", price: 0.000354, marketCap: 354550, liquidity: 42000, volume24h: 410000, change24h: 127.0, holders: 903, history: [] },
  { id: "asteroid", symbol: "ASTEROID", name: "Asteroid", price: 0.00357, marketCap: 3570000, liquidity: 210000, volume24h: 620000, change24h: -6.4, holders: 2140, history: [] },
  { id: "aurora", symbol: "AURORA", name: "Aurora", price: 0.0014, marketCap: 1400000, liquidity: 118000, volume24h: 480000, change24h: 73.8, holders: 1560, history: [] },
  { id: "deepflow", symbol: "DEEPFLOW", name: "Deepflow", price: 0.0000821, marketCap: 82140, liquidity: 16500, volume24h: 92000, change24h: 18.2, holders: 340, history: [] },
  { id: "pons", symbol: "PONS", name: "Pons", price: 0.6311, marketCap: 6311000, liquidity: 320000, volume24h: 780000, change24h: -4.4, holders: 4210, history: [] },
  { id: "uranus", symbol: "URANUS", name: "Uranus", price: 0.00111, marketCap: 1110000, liquidity: 96000, volume24h: 610000, change24h: 59.6, holders: 1870, history: [] },
  { id: "morx", symbol: "MORX", name: "Moorix", price: 0.00007812, marketCap: 77170, liquidity: 14200, volume24h: 68000, change24h: 37.8, holders: 402, history: [] },
  { id: "pprm", symbol: "PPRM", name: "PoolPrism", price: 0.000000983, marketCap: 433020, liquidity: 28000, volume24h: 190000, change24h: 928.0, holders: 1120, history: [] },
  { id: "si", symbol: "SI", name: "Slop Inu", price: 0.0000039, marketCap: 39640, liquidity: 8100, volume24h: 22000, change24h: 195.0, holders: 260, history: [] },
  { id: "bucket", symbol: "BUCKET", name: "Bucket Shop", price: 0.004648, marketCap: 4610000, liquidity: 340000, volume24h: 512000, change24h: 29.4, holders: 3050, history: [] },
  { id: "firm", symbol: "FIRM", name: "Muse Firm", price: 0.00001361, marketCap: 12920, liquidity: 3400, volume24h: 9800, change24h: -71.8, holders: 145, history: [] },
  { id: "decoded", symbol: "DECODED", name: "decOded", price: 0.00005389, marketCap: 51900, liquidity: 9600, volume24h: 31000, change24h: -5.5, holders: 318, history: [] },
];

seedTokens.forEach((token) => {
  let price = token.price * 0.85;
  const history: number[] = [];
  for (let i = 0; i < 40; i++) {
    price *= 1 + (Math.random() - 0.45) * 0.05;
    history.push(price);
  }
  history.push(token.price);
  token.history = history;
});

export const reasoningBank: Record<"BUY" | "SELL" | "CALL" | "NOTE", string[]> = {
  BUY: [
    "Volume is expanding while liquidity remains stable. Opening a small position.",
    "24h volume increased sharply while liquidity held flat. Entering ahead of a potential breakout.",
    "Momentum confirmed above the entry range. Adding exposure.",
    "Liquidity depth improved meaningfully. Comfortable sizing up here.",
  ],
  SELL: [
    "Momentum has weakened below the exit threshold. Reducing the position.",
    "Position reached the predefined take-profit level. Closing exposure.",
    "Liquidity is thinning relative to recent volume. Cutting risk.",
    "Volume is fading after the initial move. Taking profit here.",
  ],
  CALL: [
    "Watching for confirmation before entering. Momentum remains constructive.",
    "Liquidity expansion detected. Waiting for a clean entry.",
    "Setup is forming but volume needs to confirm first.",
    "Keeping this on radar while liquidity continues to build.",
  ],
  NOTE: [
    "Liquidity expansion detected across several Solana microcaps.",
    "Broad volume increase this cycle. Watching correlated pairs.",
    "Market structure remains constructive across tracked tokens.",
    "No new entries this cycle. Monitoring existing positions.",
  ],
};
